### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by sarfatiyosef** [DanWahlin/AccountAtAGlance-ASPCore#1]
hi Dan , 
link in dropbox is broken, do you have another link for xml files ?

**Comment by DanWahlin** [comment]
You'll find them at this location in the project:

https://github.com/DanWahlin/AccountAtAGlance-ASPCore/tree/master/src/AccountAtAGlance/XML

**Comment by DanWahlin** [comment]
I just updated the project to .NET Core 2 as a heads-up. Been wanting to do that for awhile and your mention about the broken link finally got me to make some time. Thanks. :-)

**Comment by sarfatiyosef** [comment]
thanks Dan your project is very helpful!

**Comment by DanWahlin** [comment]
Thanks!
